package com.biodataai.app.ui.screen

import android.app.Activity
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.lifecycle.createSavedStateHandle
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.lifecycle.viewmodel.initializer
import androidx.lifecycle.viewmodel.viewModelFactory
import androidx.compose.runtime.rememberCoroutineScope
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.navigation.NavController
import com.biodataai.app.navigation.NavRoute
import com.biodataai.app.ui.viewmodel.LoginViewModel
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import kotlinx.coroutines.launch

@Composable
fun LoginScreen(navController: NavController) {
    val context = LocalContext.current
    val firebaseAuth = FirebaseAuth.getInstance()
    // Scoped to the nav entry via a factory; uses applicationContext to avoid leaking the Activity
    // across config changes, and createSavedStateHandle() instead of the test-only constructor.
    val appContext = context.applicationContext
    val viewModel: LoginViewModel = viewModel(
        factory = viewModelFactory {
            initializer { LoginViewModel(appContext, firebaseAuth, createSavedStateHandle()) }
        }
    )

    val uiState by viewModel.uiState.collectAsState()
    val snackbarHostState = remember { SnackbarHostState() }
    val scope = rememberCoroutineScope()
    val activity = context as? Activity

    LaunchedEffect(uiState.error) {
        uiState.error?.let {
            snackbarHostState.showSnackbar(it)
        }
    }

    // Navigate to Home on successful login
    LaunchedEffect(firebaseAuth.currentUser) {
        if (firebaseAuth.currentUser != null) {
            navController.navigate(NavRoute.Home) {
                popUpTo(NavRoute.Auth.Login) { inclusive = true }
            }
        }
    }

    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = Alignment.Center
    ) {
        SnackbarHost(snackbarHostState, modifier = Modifier.align(Alignment.BottomCenter))

        if (uiState.phoneOtpFlow == null) {
            // Login button screen
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                modifier = Modifier.padding(16.dp)
            ) {
                Text("BioData AI")
                Spacer(Modifier.height(32.dp))
                Text("Create your marriage biodata")
                Spacer(Modifier.height(48.dp))

                Button(
                    onClick = {
                        // default_web_client_id is auto-generated by the google-services plugin
                        // once google-services.json contains a web OAuth client (i.e. Google
                        // sign-in is enabled in Firebase). Look it up at runtime so the app still
                        // compiles before that's configured.
                        val resId = context.resources.getIdentifier(
                            "default_web_client_id", "string", context.packageName
                        )
                        val webClientId = if (resId != 0) context.getString(resId) else null
                        if (webClientId == null || activity == null) {
                            scope.launch {
                                snackbarHostState.showSnackbar(
                                    "Google Sign-In isn't configured yet. Enable Google in Firebase " +
                                        "Authentication and re-download google-services.json."
                                )
                            }
                        } else {
                            scope.launch {
                                try {
                                    val option = GetSignInWithGoogleOption.Builder(webClientId).build()
                                    val request = GetCredentialRequest.Builder()
                                        .addCredentialOption(option)
                                        .build()
                                    val result = CredentialManager.create(context)
                                        .getCredential(activity, request)
                                    val cred = result.credential
                                    if (cred is CustomCredential &&
                                        cred.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                                    ) {
                                        val googleCred = GoogleIdTokenCredential.createFrom(cred.data)
                                        viewModel.signInWithGoogle(googleCred.idToken)
                                    } else {
                                        snackbarHostState.showSnackbar("Unexpected sign-in credential type.")
                                    }
                                } catch (e: Exception) {
                                    snackbarHostState.showSnackbar("Google Sign-In failed: ${e.message}")
                                }
                            }
                        }
                    },
                    modifier = Modifier.padding(16.dp),
                    enabled = !uiState.isLoading
                ) {
                    Text("Continue with Google")
                }

                Button(
                    onClick = { viewModel.startPhoneOtp() },
                    modifier = Modifier.padding(16.dp),
                    enabled = !uiState.isLoading
                ) {
                    Text("Continue with Phone")
                }

                if (uiState.isLoading) {
                    Spacer(Modifier.height(24.dp))
                    CircularProgressIndicator()
                }
            }
        } else {
            // Phone OTP flow
            val flow = uiState.phoneOtpFlow
            if (flow != null) {
                PhoneOtpScreen(
                    flow = flow,
                    isLoading = uiState.isLoading,
                    onPhoneSubmit = { phone ->
                        if (activity != null) {
                            viewModel.submitPhoneNumber(activity, phone)
                        } else {
                            scope.launch { snackbarHostState.showSnackbar("Cannot start phone verification.") }
                        }
                    },
                    onOtpSubmit = { viewModel.submitOtp(it) },
                    onCancel = { viewModel.cancelPhoneOtp() }
                )
            }
        }
    }
}

@Composable
private fun PhoneOtpScreen(
    flow: com.biodataai.app.ui.viewmodel.PhoneOtpFlow,
    isLoading: Boolean,
    onPhoneSubmit: (String) -> Unit,
    onOtpSubmit: (String) -> Unit,
    onCancel: () -> Unit
) {
    var phoneInput by remember { mutableStateOf(flow.phoneNumber) }
    var otpInput by remember { mutableStateOf("") }

    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.padding(16.dp)
    ) {
        Text("Phone Verification")
        Spacer(Modifier.height(24.dp))

        if (flow.step == 1) {
            OutlinedTextField(
                value = phoneInput,
                onValueChange = { phoneInput = it },
                label = { Text("Phone Number") },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Phone),
                enabled = !isLoading
            )
            Spacer(Modifier.height(16.dp))
            Button(
                onClick = { onPhoneSubmit(phoneInput) },
                enabled = !isLoading && phoneInput.isNotBlank()
            ) {
                Text("Send OTP")
            }
        } else if (flow.step == 2) {
            Text("Enter OTP sent to ${flow.phoneNumber}")
            Spacer(Modifier.height(16.dp))
            OutlinedTextField(
                value = otpInput,
                onValueChange = { otpInput = it },
                label = { Text("OTP") },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                enabled = !isLoading
            )
            Spacer(Modifier.height(16.dp))
            Button(
                onClick = { onOtpSubmit(otpInput) },
                enabled = !isLoading && otpInput.isNotBlank()
            ) {
                Text("Verify")
            }
        }

        Spacer(Modifier.height(16.dp))
        Button(
            onClick = { onCancel() },
            enabled = !isLoading
        ) {
            Text("Cancel")
        }

        if (isLoading) {
            Spacer(Modifier.height(24.dp))
            CircularProgressIndicator()
        }
    }
}
